name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm dependencies
        uses: ./.github/actions/pnpm-install

      - name: Build
        run: pnpm run build

  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm dependencies
        uses: ./.github/actions/pnpm-install

      - name: Check style
        run: pnpm exec prettier --check .
