name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  cache-and-install:
    name: Cache and Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache data for pnpm and node_modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: cache-and-install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Reusable Action for PNPM and NX
        uses: dipiash/pnpm-nx-reusable-action@v2

      - name: Build
        run: pnpm run build

  style:
    name: Style
    runs-on: ubuntu-latest
    needs: cache-and-install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Reusable Action for PNPM and NX
        uses: dipiash/pnpm-nx-reusable-action@v2

      - name: Check style
        run: pnpm exec prettier --check .
